# Generated by Django 4.2.16 on 2026-09-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorite_type',
            field=models.CharField(choices=[('job', 'Job'), ('property', 'Property'), ('vehicle', 'Vehicle'), ('service', 'Service'), ('service_provider', 'Service Provider'), ('news', 'News'), ('article', 'Article'), ('market', 'Market'), ('classified', 'Classified')], db_column='content_type', max_length=30),
        ),
    ]
