# Generated by Django 4.2.16 on 2026-07-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='স্লাইডারের শিরোনাম', max_length=500)),
                ('title_bn', models.CharField(blank=True, help_text='শিরোনাম (বাংলা)', max_length=500)),
                ('subtitle', models.CharField(blank=True, help_text='সাবটাইটেল', max_length=500)),
                ('subtitle_bn', models.CharField(blank=True, help_text='সাবটাইটেল (বাংলা)', max_length=500)),
                ('image', models.ImageField(help_text='ব্যানার ইমেজ (১২০০x৪০০ পিক্সেল রেকমেন্ডেড)', upload_to='sliders/')),
                ('cta_text', models.CharField(default='বিস্তারিত দেখুন', help_text='বাটনের টেক্সট', max_length=100)),
                ('link', models.CharField(default='/', help_text='রিডাইরেক্ট URL (যেমন /jobs বা https://example.com)', max_length=500)),
                ('is_external', models.BooleanField(default=False, help_text='এক্সটার্নাল লিঙ্ক হলে চেক করুন')),
                ('overlay_gradient', models.CharField(default='from-blue-950/85 via-blue-900/55 to-transparent', help_text='CSS gradient class for text readability overlay', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='ক্রম (ছোট সংখ্যা আগে দেখাবে)')),
                ('is_active', models.BooleanField(default=True, help_text='অ্যাক্টিভ/ডিঅ্যাক্টিভ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
