# Generated by Django 4.2.16 on 2026-09-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='country',
            field=models.CharField(choices=[('oman', 'Oman'), ('saudi', 'Saudi Arabia')], default='oman', max_length=10),
        ),
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.CharField(choices=[('oman', 'Oman'), ('saudi', 'Saudi Arabia')], default='oman', max_length=10),
        ),
    ]
