# Generated by Django 4.2.16 on 2026-07-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_posts/'),
        ),
    ]
