# Generated by Django 4.2.16 on 2026-07-14 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_bn', models.CharField(blank=True, max_length=255, verbose_name='Bengali Name')),
                ('service_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('fire', 'Fire Service'), ('police', 'Police'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('blood_bank', 'Blood Bank')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('is_24_7', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('description_bn', models.TextField(blank=True, verbose_name='Bengali Description')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'service_type', 'name'],
                'indexes': [models.Index(fields=['service_type'], name='emergency_e_service_a89ccd_idx'), models.Index(fields=['is_active'], name='emergency_e_is_acti_18a366_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user'], name='emergency_e_user_id_6870af_idx')],
            },
        ),
    ]
