# Generated by Django 4.2.16 on 2026-07-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedimage',
            name='content_type',
            field=models.CharField(choices=[('job', 'Job'), ('property', 'Property'), ('vehicle', 'Vehicle'), ('service', 'Service'), ('classified', 'Classified'), ('others', 'Others')], max_length=20),
        ),
    ]
