# Generated by Django 4.2.16 on 2026-08-26 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifieds', '0003_job_rating_job_review_count_property_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_title', models.CharField(max_length=255)),
                ('professional_title_bn', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('summary_bn', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='OMR', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='job_seekers/pictures/')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='job_seekers/cvs/')),
                ('status', models.CharField(choices=[('ACTIVELY_LOOKING', 'Actively Looking'), ('HIRED', 'Hired / Not Looking'), ('HIDDEN', 'Hidden')], default='ACTIVELY_LOOKING', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='classifieds_slug_2089a3_idx'), models.Index(fields=['status'], name='classifieds_status_21120b_idx'), models.Index(fields=['user'], name='classifieds_user_id_eb385c_idx')],
            },
        ),
    ]
