# Generated by Django 4.2.16 on 2026-09-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0005_jobseekerprofile_area_jobseekerprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(choices=[('oman', 'Oman'), ('saudi', 'Saudi Arabia')], default='oman', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='country',
            field=models.CharField(choices=[('oman', 'Oman'), ('saudi', 'Saudi Arabia')], default='oman', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.CharField(choices=[('oman', 'Oman'), ('saudi', 'Saudi Arabia')], default='oman', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='country',
            field=models.CharField(choices=[('oman', 'Oman'), ('saudi', 'Saudi Arabia')], default='oman', max_length=10),
        ),
    ]
