# Generated by Django 4.2.16 on 2026-09-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0006_job_country_property_country_service_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Specialist Doctor', 'Specialist Doctor'), ('Hospital', 'Hospital'), ('Ambulance', 'Ambulance'), ('Police Station', 'Police Station'), ('Embassy', 'Embassy'), ('Travel Agency', 'Travel Agency'), ('Hotel', 'Hotel'), ('Maktab Sanad', 'Maktab Sanad'), ('Money Exchange', 'Money Exchange'), ('Lawyer', 'Lawyer'), ('Tourist Place', 'Tourist Place'), ('Cleaning', 'Cleaning'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('AC Repair', 'AC Repair'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting'), ('Appliance Repair', 'Appliance Repair'), ('Sweeper', 'Sweeper'), ('Mason', 'Mason'), ('Mobile Technician', 'Mobile Technician'), ('Pest Control', 'Pest Control'), ('Insurance', 'Insurance'), ('Business', 'Business'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
